# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: swans-webapp

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  region: eu-west-2

plugins:
  - serverless-finch

custom:
  env: ${opt:stage, 'dev'}
  bucketPrefixes:
    dev: dev
    prod: www
  client:
    bucketName: ${self:custom.bucketPrefixes.${self:custom.env}}.swans.app
    distributionFolder: dist/
