source 'https://rubygems.org'

group :test do
  gem 'config', '~> 1.7.0'
  gem 'cucumber', '~> 3.1.0'
  gem 'httparty', '~> 0.16.2'
  gem 'rspec', '~> 3.7.0'
  gem 'rspec-json_expectations', '~> 2.1.0'
  gem 'net-sftp', '~> 2.1.2'
  gem 'waitutil', '~> 0.2.1'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'parallel'
end
